SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(SUBSTRING(PRODUCT_CODE, 1, 2)) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY
# SELECT가 GROUP BY보다 먼저 실행되므로 alias를 이용

# GROUP BY로 이미 묶였으므로 *를 이용해도 됨
SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY